@extends('layout.template')

@section('content')
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <th>Frendy</th>
                <th>523180</th>
                <th>A</th>
            </tr>
            <tr>
                <th>1</th>
                <th>Ammar</th>
                <th>518147</th>
                <th>A</th>
            </tr>
            <tr>
                <th>1</th>
                <th>Aditya</th>
                <th>523550</th>
                <th>B</th>
            </tr>
            <tr>
                <th>1</th>
                <th>Ridho</th>
                <th>524130</th>
                <th>B</th>
            </tr>
            <tr>
                <th>1</th>
                <th>Raihan</th>
                <th>524257</th>
                <th>A</th>
            </tr>
        </tbody>
    </table>
@endsection
